security:
    providers:
        main:
            id: 'App\Security\UserProvider'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
                path: 'app_logout'
            webauthn:
                registration:
                    enabled: true
    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/add/device,  roles: IS_AUTHENTICATED_FULLY }
